flags: {}
packages:
- .
extra-deps:
- async-2.1.1.1
- attoparsec-0.13.2.0
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- conduit-1.2.12
- conduit-extra-1.1.17
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.8.0.3
- exceptions-0.8.3
- gi-glib-2.0.14
- gi-gobject-2.0.15
- hashable-1.2.6.1
- haskell-gi-0.20.3
- haskell-gi-base-0.20.4
- haskell-gi-overloading-1.0
- haskell-lexer-1.0.1
- integer-logarithms-1.0.2
- lifted-base-0.2.3.11
- mmorph-1.1.0
- monad-control-1.0.2.2
- mtl-2.2.1
- network-2.6.3.2
- old-locale-1.0.0.7
- parsec-3.1.11
- pretty-show-1.6.13
- primitive-0.6.2.0
- random-1.1
- regex-base-0.93.2
- regex-tdfa-1.2.2
- resourcet-1.1.9
- safe-0.3.15
- scientific-0.3.5.2
- stm-2.4.4.1
- streaming-commons-0.1.18
- text-1.2.2.2
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- xdg-basedir-0.2.2
- xml-conduit-1.4.0.4
- xml-types-0.3.6
- zlib-0.6.1.2
resolver: ghc-8.2.1
